name = "ModuleLogger"
uuid = "247fc82d-8a48-4c99-91f9-777a8789624c"
authors = ["Tom Kwong <tk3369@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
